homepage:
    pattern:  /
    defaults: { _controller: UsuariosBundle:Default:index }
    
BackendBundle:
    resource: "@UsuariosBundle/Resources/config/routing.yml"
    prefix:   /usuario

ContactosBundle:
    resource: "@ContactosBundle/Resources/config/routing.yml"
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
