parameters:
#    contactos.example.class: Agenda\contactosBundle\Example

services:
#    contactos.example:
#        class: %contactos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
