contacto:
    pattern:  /list
    defaults: { _controller: "ContactosBundle:Agenda:index" }

contacto_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContactosBundle:Agenda:show" }

contacto_new:
    pattern:  /new
    defaults: { _controller: "ContactosBundle:Agenda:new" }

contacto_create:
    pattern:  /create
    defaults: { _controller: "ContactosBundle:Agenda:create" }
    requirements: { _method: post }

contacto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContactosBundle:Agenda:edit" }

contacto_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContactosBundle:Agenda:update" }
    requirements: { _method: post }

contacto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContactosBundle:Agenda:delete" }
    requirements: { _method: post }
